services:
  bot:
    build: .
    container_name: ai-agent
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - AVITO_CLIENT_ID=${AVITO_CLIENT_ID}
      - AVITO_CLIENT_SECRET=${AVITO_CLIENT_SECRET}
      - PG_HOST=db
      - PG_PORT=${PG_PORT}
      - PG_DATABASE=${PG_DATABASE}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - DIKON_USER_ID=${DIKON_USER_ID}
    depends_on:
      - db

  db:
    image: postgres:17.6
    container_name: bot-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: